framework:
  base_path: ./
  default_agent: InitialAgent
  pre_prompt: >
    You are an experienced Executive Assistant. Your task is to manage communication and coordination between team members, stakeholders, and clients.
  
    Other agents you can collaborate with:
    $otherAgents
  
    Tools at your disposal:
    $tools
  
    When given a task, think through the problem step-by-step, consider the roles and capabilities of other agents, and use the available tools when necessary. Provide detailed explanations of your thought process and decisions.

  post_prompt: >
      Role: {agent.role}
      Previous Context: {agent.memory}
      Knowledge: {agent.role_knowledge}
      Current Input: {input_data}
  
      Task: Process the input based on your role, knowledge, and the instructions above. 
      Provide your thoughts and any necessary JSON updates.
      Suggest the next action or agent to handle the task.
    
      Format your response as follows:
      THOUGHTS: [Your reasoning process]
      USE_TOOL: [Optional: Specify a tool to use, {"tool_name": {"parameter": "value", "parameter": "value"} } ]
      NEXT_ACTION: [Suggest the next action or agent, e.g., NEXT_AGENT: DeveloperAgent or FINISH if the task is complete]
  
      Begin your response now:

  tool_extract_methods:
    - name: json_format
      regexp: 'USE_TOOL:\s*(\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\})'
      parse_method: json
      tool_name_extractor: '"(\w+)"'
      params_extractor: ':\s*(\{.*?\})(?=\s*\})'  # Changed this line
    - name: named_with_json
      regexp: 'USE_TOOL:\s*(\w+)\s+with\s+(\{(?:[^{}]|\{(?:[^{}]|\{[^{}]*\})*\})*\})'
      parse_method: json_with_name
      tool_name_extractor: '^(\w+)'
      params_extractor: '(\{.*\})$'
    - name: named_with_key_value
      regexp: 'USE_TOOL:\s*(\w+)\s+with\s+(.+)'
      parse_method: key_value_with_name
      tool_name_extractor: '^(\w+)'
      params_extractor: '(?<=with\s)(.+)$'

llm:
  openai:
    api_key: ${OPENAI_API_KEY}
    default_model: gpt-3.5-turbo
  ollama:
    api_base: http://localhost:11434
    default_model: openhermes:latest

agents:
  - DeveloperAgent
  - DesignerAgent
  - ProductManagerAgent

tools_path: ./Tools
role_knowledge_path: ./RoleKnowledge




logging:
  level: INFO
  file: framework.log
